
services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: agriconnect_db
      POSTGRES_USER: agriconnect_user
      POSTGRES_PASSWORD: agriconnect_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agriconnect_user -d agriconnect_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: farmlink_redis
    ports:
      - "6379:6379"
      
volumes:
  postgres_data: